//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charaterizator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string COMComutator {
            get {
                return ((string)(this["COMComutator"]));
            }
            set {
                this["COMComutator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string COMMensor {
            get {
                return ((string)(this["COMMensor"]));
            }
            set {
                this["COMMensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string COMMultimetr {
            get {
                return ((string)(this["COMMultimetr"]));
            }
            set {
                this["COMMultimetr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string COMSensor {
            get {
                return ((string)(this["COMSensor"]));
            }
            set {
                this["COMSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09/18/2019 17:23:00")]
        public global::System.DateTime Data {
            get {
                return ((global::System.DateTime)(this["Data"]));
            }
            set {
                this["Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int COMComutator_Speed {
            get {
                return ((int)(this["COMComutator_Speed"]));
            }
            set {
                this["COMComutator_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMComutator_Parity {
            get {
                return ((int)(this["COMComutator_Parity"]));
            }
            set {
                this["COMComutator_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int COMComutator_StopBits {
            get {
                return ((int)(this["COMComutator_StopBits"]));
            }
            set {
                this["COMComutator_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int COMComutator_DataBits {
            get {
                return ((int)(this["COMComutator_DataBits"]));
            }
            set {
                this["COMComutator_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int COMMensor_Speed {
            get {
                return ((int)(this["COMMensor_Speed"]));
            }
            set {
                this["COMMensor_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMMensor_Parity {
            get {
                return ((int)(this["COMMensor_Parity"]));
            }
            set {
                this["COMMensor_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int COMMensor_StopBits {
            get {
                return ((int)(this["COMMensor_StopBits"]));
            }
            set {
                this["COMMensor_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int COMMensor_DataBits {
            get {
                return ((int)(this["COMMensor_DataBits"]));
            }
            set {
                this["COMMensor_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2400")]
        public int COMMultimetr_Speed {
            get {
                return ((int)(this["COMMultimetr_Speed"]));
            }
            set {
                this["COMMultimetr_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMMultimetr_Parity {
            get {
                return ((int)(this["COMMultimetr_Parity"]));
            }
            set {
                this["COMMultimetr_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int COMMultimetr_StopBits {
            get {
                return ((int)(this["COMMultimetr_StopBits"]));
            }
            set {
                this["COMMultimetr_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int COMMultimetr_DatabBits {
            get {
                return ((int)(this["COMMultimetr_DatabBits"]));
            }
            set {
                this["COMMultimetr_DatabBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int COMSensor_Speed {
            get {
                return ((int)(this["COMSensor_Speed"]));
            }
            set {
                this["COMSensor_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMSensor_Parity {
            get {
                return ((int)(this["COMSensor_Parity"]));
            }
            set {
                this["COMSensor_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int COMSensor_StopBits {
            get {
                return ((int)(this["COMSensor_StopBits"]));
            }
            set {
                this["COMSensor_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int COMSensor_DataBits {
            get {
                return ((int)(this["COMSensor_DataBits"]));
            }
            set {
                this["COMSensor_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Параметр {
            get {
                return ((int)(this["Параметр"]));
            }
            set {
                this["Параметр"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string COMColdCamera {
            get {
                return ((string)(this["COMColdCamera"]));
            }
            set {
                this["COMColdCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int COMColdCamera_Speed {
            get {
                return ((int)(this["COMColdCamera_Speed"]));
            }
            set {
                this["COMColdCamera_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMColdCamera_Parity {
            get {
                return ((int)(this["COMColdCamera_Parity"]));
            }
            set {
                this["COMColdCamera_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int COMColdCamera_StopBits {
            get {
                return ((int)(this["COMColdCamera_StopBits"]));
            }
            set {
                this["COMColdCamera_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int COMColdCamera_DataBits {
            get {
                return ((int)(this["COMColdCamera_DataBits"]));
            }
            set {
                this["COMColdCamera_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MaxChannalCount {
            get {
                return ((int)(this["MaxChannalCount"]));
            }
            set {
                this["MaxChannalCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CommutatorSwitchDelay {
            get {
                return ((int)(this["CommutatorSwitchDelay"]));
            }
            set {
                this["CommutatorSwitchDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\WORK\\\\BBMW\\\\Repozitoriy\\\\Fail174\\\\Charakterizator\\\\Charaterizator\\\\SensorsDB\\" +
            "\\Sensors.mdb")]
        public string FileNameDB {
            get {
                return ((string)(this["FileNameDB"]));
            }
            set {
                this["FileNameDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_HoldTimeTemp {
            get {
                return ((double)(this["set_HoldTimeTemp"]));
            }
            set {
                this["set_HoldTimeTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_HoldTimePress {
            get {
                return ((double)(this["set_HoldTimePress"]));
            }
            set {
                this["set_HoldTimePress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_HoldTimeAfReset {
            get {
                return ((double)(this["set_HoldTimeAfReset"]));
            }
            set {
                this["set_HoldTimeAfReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_DeltaTemp {
            get {
                return ((double)(this["set_DeltaTemp"]));
            }
            set {
                this["set_DeltaTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_DeltaPress {
            get {
                return ((double)(this["set_DeltaPress"]));
            }
            set {
                this["set_DeltaPress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool set_HandleContrPress {
            get {
                return ((bool)(this["set_HandleContrPress"]));
            }
            set {
                this["set_HandleContrPress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool set_HandleContrMultimetr {
            get {
                return ((bool)(this["set_HandleContrMultimetr"]));
            }
            set {
                this["set_HandleContrMultimetr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_MainTimer {
            get {
                return ((double)(this["set_MainTimer"]));
            }
            set {
                this["set_MainTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int set_CommReadCH {
            get {
                return ((int)(this["set_CommReadCH"]));
            }
            set {
                this["set_CommReadCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int set_CommMaxSetCH {
            get {
                return ((int)(this["set_CommMaxSetCH"]));
            }
            set {
                this["set_CommMaxSetCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_CommReadPeriod {
            get {
                return ((double)(this["set_CommReadPeriod"]));
            }
            set {
                this["set_CommReadPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_CommReadPause {
            get {
                return ((double)(this["set_CommReadPause"]));
            }
            set {
                this["set_CommReadPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int set_MultimReadCount {
            get {
                return ((int)(this["set_MultimReadCount"]));
            }
            set {
                this["set_MultimReadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int set_MultimReadPeriod {
            get {
                return ((int)(this["set_MultimReadPeriod"]));
            }
            set {
                this["set_MultimReadPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_MensorReadPeriod {
            get {
                return ((double)(this["set_MensorReadPeriod"]));
            }
            set {
                this["set_MensorReadPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_MensorReadPause {
            get {
                return ((double)(this["set_MensorReadPause"]));
            }
            set {
                this["set_MensorReadPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool set_MensorSetZero {
            get {
                return ((bool)(this["set_MensorSetZero"]));
            }
            set {
                this["set_MensorSetZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int set_SensReadCount {
            get {
                return ((int)(this["set_SensReadCount"]));
            }
            set {
                this["set_SensReadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int set_SensReadPause {
            get {
                return ((int)(this["set_SensReadPause"]));
            }
            set {
                this["set_SensReadPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_TCameraReadPeriod {
            get {
                return ((double)(this["set_TCameraReadPeriod"]));
            }
            set {
                this["set_TCameraReadPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int set_SensWaitTimeout {
            get {
                return ((int)(this["set_SensWaitTimeout"]));
            }
            set {
                this["set_SensWaitTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int set_MultimReadTimeout {
            get {
                return ((int)(this["set_MultimReadTimeout"]));
            }
            set {
                this["set_MultimReadTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int set_MultimDataReady {
            get {
                return ((int)(this["set_MultimDataReady"]));
            }
            set {
                this["set_MultimDataReady"] = value;
            }
        }
    }
}
